In [1]:
### All imports we will need
import cv2
import numpy as np
import math
import glob
import matplotlib.pyplot as plt

In [2]:
IN_DEBUG=False ## sets DEBUG false to avoid running assertions on incomplete requirements

%run ./utils.ipynb  ## this line runs the utils notebook and imports it into the current notebook

# use interactive plots
%matplotlib notebook
## you will need to re-run this cell every time you change something in the utils notebook
## DONOT forget to save the utils notebook before running this cell

In [3]:
# img = cv2.imread('imgs/image1.jpg')
# # cv2.imshow('image', img)
# # edit_image=preprocess(img)
# # cv2.imshow('edit_image', edit_image)
# gray_scale= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )
# contours, hierarchy = cv2.findContours(gray_scale, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contours))

In [4]:
#Read Img
# img = cv2.imread('imgs/image4.jpg')
img = cv2.imread('car/test.png')


#Convert To Gray Scale
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#Edge Detection [i/p must be gray Scale image]
edges = cv2.Canny(gray,50,150,apertureSize = 3)#there is some noise here we need to remove it

# show_images([img,gray,edges],['Original','Gray Scale','Edged Image'])


# Hough Lines Detection
# To apply the Transform, first an edge detection pre-processing is desirable.
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100, minLineLength=100, maxLineGap=50)

# Draw lines on the image
Straight_Lines=np.copy(img)
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(Straight_Lines, (x1, y1), (x2, y2), (255, 0, 0), 3)

# Matrix of Endpoints and start points of the straight lines
Straight_Lines_Matrix=np.ones(np.shape(img)[0:2])
for line in lines:
    x1, y1, x2, y2 = line[0]
    Straight_Lines_Matrix[y1,x1]=0
    Straight_Lines_Matrix[y2,x2]=0
#     print('x1:',x1,'y1:',y1,'x2:',x2,'y2:',y2)
# print(lines)

# show_images([Straight_Lines,Straight_Lines_Matrix],['Straight Lines','Straight Lines Matrix'])


In [5]:
# Car Detetction :D

#Read Img
img = cv2.imread('car/test.png')

# For better accuracy, use binary images. So before finding contours, apply threshold or canny edge detection
# Convert To Gray Scale
binary = toBianry(img)

# show_images([img,binary],['Original','Binary Image'])

#Getting Contours in image
# 1st parm: source image
# 2nd parm: contour retrieval mode
# 3rd parm: contour approximation method cv2.CHAIN_APPROX_SIMPLE[Memory saved not all points are stored]
#o/p: the contours and hierarchy.
contours, hierarchy = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#Sort Contours Descending
contours = sorted(contours, key=cv2.contourArea, reverse=True)
print(len(contours))


#Draw Contours
img_contours=np.copy(img)
# 3rd parm: To draw all the contours in an image (-1) or To draw an individual contour, say 3th contour (2)
# 4th & 5th parm: color and thickness prespectively :)
cv2.drawContours(img_contours, contours[0], -1, (255, 0, 0), 5)
# show_images([img_contours],['Contours'])



29


array([[[ 75, 110, 153],
        [ 82, 118, 158],
        [ 87, 122, 162],
        ...,
        [102, 143, 166],
        [101, 142, 165],
        [101, 142, 165]],

       [[ 65, 100, 143],
        [ 73, 108, 151],
        [ 82, 117, 157],
        ...,
        [101, 142, 165],
        [ 99, 140, 163],
        [ 99, 140, 163]],

       [[ 53,  88, 132],
        [ 62,  97, 140],
        [ 73, 108, 148],
        ...,
        [100, 141, 164],
        [ 97, 138, 161],
        [ 96, 137, 160]],

       ...,

       [[156, 187, 180],
        [157, 188, 181],
        [158, 186, 180],
        ...,
        [ 58,  17,  55],
        [ 55,  12,  57],
        [ 60,  19,  64]],

       [[155, 186, 179],
        [156, 187, 180],
        [156, 184, 178],
        ...,
        [ 73,  32,  70],
        [ 60,  17,  60],
        [ 63,  22,  67]],

       [[155, 186, 179],
        [156, 187, 180],
        [154, 185, 178],
        ...,
        [ 88,  47,  84],
        [ 68,  26,  67],
        [ 64,  24,  66]]

In [6]:
import cv2
import numpy as np
 
image_original = cv2.imread('car/test.png')
# cv2.imshow("Original", image_original)
 
result = image_original.copy()
 
image = cv2.cvtColor(image_original, cv2.COLOR_BGR2HSV)
 
# lower boundary RED color range values; Hue (0 - 10)
lower1 = np.array([0, 100, 20])
upper1 = np.array([10, 255, 255])

# upper boundary RED color range values; Hue (160 - 180)
lower2 = np.array([160,100,20])
upper2 = np.array([179,255,255])
 
lower_mask = cv2.inRange(image, lower1, upper1)
upper_mask = cv2.inRange(image, lower2, upper2)
 
full_mask = lower_mask + upper_mask;
 
result = cv2.bitwise_and(result, result, mask=full_mask)
 
# cv2.imshow('mask', full_mask)
# cv2.imshow('result', result)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#Getting Contours in image
# 1st parm: source image
# 2nd parm: contour retrieval mode
# 3rd parm: contour approximation method cv2.CHAIN_APPROX_SIMPLE[Memory saved not all points are stored]
#o/p: the contours and hierarchy.
contours, hierarchy = cv2.findContours(full_mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#Sort Contours Descending
contours = sorted(contours, key=cv2.contourArea, reverse=True)
print(len(contours))
# print((contours))


#Draw Contours
img_contours=np.copy(result)
# 3rd parm: To draw all the contours in an image (-1) or To draw an individual contour, say 3th contour (2)
# 4th & 5th parm: color and thickness prespectively :)
# countors_image=np.copy(image_original)
# cv2.drawContours(countors_image, contours[0], -1, (255, 0, 0), 5)
# show_images([countors_image],['Contours'])
# print(np.shape(countors_image))


# print(contours[0])

# Draming Rectangle :D
rectangle_image=np.copy(image_original)
rect = cv2.minAreaRect(contours[0])
box = cv2.boxPoints(rect)
box = np.int0(box)
cv2.drawContours(rectangle_image,[box],0,(0,255,0),10)



#Getting Center and angle of rotation of Rectangle
((x, y), (width, height), angle_of_rotation) = cv2.minAreaRect(box)
hCar= max(width, height)
wCar= min(width, height)
xCar=x
yCar=y
print("x:",x,"y:",y,"width:",wCar,"height:",hCar)
print(angle_of_rotation)

# show_images([rectangle_image],['Car Rectangle'],BGR=True)

print(box)
print(rect)

# print(box.angle)

248
x: 420.0 y: 665.5 width: 130.0 height: 153.0
90.0
[[355 589]
 [485 589]
 [485 742]
 [355 742]]
((420.0, 665.5), (153.0, 130.0), 90.0)


In [8]:
# find line of on which car is on
xCar=x
yCar=y
# lines.dropna(inplace=True)
# for line in lines:
#     x1, y1, x2, y2 = line[0]
#     if(on_line (x1,y1,x2,y2,xCar,yCar,maxthershold=20)):
#         print("Found @ x",x1," y",y1)
#         image_original[x1-10:x1+10,y1-10:y1+10]=(255,255,255)
#         #Getting Distance from this Center to the start of the straight line
#         cv2.imshow("Original", image_original)
 


In [9]:
print(lines)

[[[ 896   13  962  957]]

 [[ 428 1138  779 1138]]

 [[ 134  612  141  403]]

 [[  23  783   32  622]]

 [[ 622    5  958    0]]

 [[ 858  579  888 1009]]

 [[ 918   26  971 1030]]

 [[ 457 1103  763 1103]]

 [[ 140  458  151  140]]

 [[ 430  629  430  440]]

 [[ 916   25  971 1080]]

 [[   0 1204    6 1076]]

 [[ 429  439  429  200]]

 [[ 715    2  873    0]]

 [[ 917   26  970 1030]]

 [[   1  918   65    3]]

 [[ 952    1  969  989]]

 [[   0  907   44   72]]

 [[ 954    1  971 1006]]

 [[ 905    4  942  713]]

 [[ 587 1200  904 1205]]

 [[  88  921   93  821]]

 [[ 955    1  970  846]]

 [[ 906    2  937  599]]

 [[   6 1211  484 1194]]

 [[ 460  594  460  367]]

 [[   6 1066   12  947]]

 [[ 914   24  965  987]]

 [[ 922   23  971  958]]

 [[ 292  316  427  314]]

 [[  99  710  111  387]]

 [[ 958   15  971  797]]

 [[   8  904   34  526]]

 [[   7  904   53   21]]

 [[ 912   23  956  852]]

 [[ 279   11  679    4]]

 [[ 840  780  854  994]]

 [[ 174  720  179  467]]

 [[  58  113

In [10]:
p=4

img=cv2.imread('car/test.png')
bina=toBianry(img)
bina[(bina==255)]=1
cv2.imshow('image',img)
cv2.imshow('binary',bina)
# show_images(binary_image)
prvx=xCar
prvy=yCar
sizey=bina.shape[0]
sizex=bina.shape[1]
threshx=int(sizex/25)
threshy=int(sizey/25)
find=0
while (prvx<sizex and prvy < sizey and find<p*hCar):
    curx=int(prvx)
    cury=int(prvy)
    if(int(angle_of_rotation)==90):
        cury-=1
    elif(int(angle_of_rotation)==180):
        cury+=1
    there=False
    for i in range (0,threshx):
        for j in range (0,threshy):
            there |=  bina[cury-i,curx-j]
    for i in range (0,threshx):
        for j in range (0,threshy):
            there |=  bina[cury+i,curx+j]
    if(curx<sizex and cury < sizey and there):
        prvx=curx
        prvy=cury
        find+=1
    else :
        print(curx,cury,there)
        print(bina[cury-threshx:cury+threshx,curx-threshy:curx+threshy])
        cv2.imshow('error',bina[cury-threshx:cury+threshx,curx-threshy:curx+threshy])
        break
print(find)
print(hCar)
print(find==p*hCar)
if(find<p*hCar):
    print('there is no way in front of the car')
else :
    print('there is a way in front of the car')
# print(prvx)
# print(prvy)

612
153.0
True
there is a way in front of the car


# 