In [1]:
### All imports we will need
import cv2
import numpy as np
import math
import glob
import matplotlib.pyplot as plt

In [2]:
IN_DEBUG=False ## sets DEBUG false to avoid running assertions on incomplete requirements

%run ./utils.ipynb  ## this line runs the utils notebook and imports it into the current notebook

# use interactive plots
%matplotlib notebook
## you will need to re-run this cell every time you change something in the utils notebook
## DONOT forget to save the utils notebook before running this cell

In [3]:
# img = cv2.imread('imgs/image1.jpg')
# # cv2.imshow('image', img)
# # edit_image=preprocess(img)
# # cv2.imshow('edit_image', edit_image)
# gray_scale= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )
# contours, hierarchy = cv2.findContours(gray_scale, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contours))

In [4]:
#Read Img
# img = cv2.imread('imgs/image4.jpg')
img = cv2.imread('car/test.png')


#Convert To Gray Scale
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#Edge Detection [i/p must be gray Scale image]
edges = cv2.Canny(gray,50,150,apertureSize = 3)#there is some noise here we need to remove it

# show_images([img,gray,edges],['Original','Gray Scale','Edged Image'])


# Hough Lines Detection
# To apply the Transform, first an edge detection pre-processing is desirable.
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100, minLineLength=100, maxLineGap=50)

# Draw lines on the image
Straight_Lines=np.copy(img)
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(Straight_Lines, (x1, y1), (x2, y2), (255, 0, 0), 3)

# Matrix of Endpoints and start points of the straight lines
Straight_Lines_Matrix=np.ones(np.shape(img)[0:2])
for line in lines:
    x1, y1, x2, y2 = line[0]
    Straight_Lines_Matrix[y1,x1]=0
    Straight_Lines_Matrix[y2,x2]=0
#     print('x1:',x1,'y1:',y1,'x2:',x2,'y2:',y2)
# print(lines)

# show_images([Straight_Lines,Straight_Lines_Matrix],['Straight Lines','Straight Lines Matrix'])


In [5]:
# Car Detetction :D

#Read Img
img = cv2.imread('car/test.png')

# For better accuracy, use binary images. So before finding contours, apply threshold or canny edge detection
# Convert To Gray Scale
binary = toBianry(img)

# show_images([img,binary],['Original','Binary Image'])

#Getting Contours in image
# 1st parm: source image
# 2nd parm: contour retrieval mode
# 3rd parm: contour approximation method cv2.CHAIN_APPROX_SIMPLE[Memory saved not all points are stored]
#o/p: the contours and hierarchy.
contours, hierarchy = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#Sort Contours Descending
contours = sorted(contours, key=cv2.contourArea, reverse=True)
print(len(contours))


#Draw Contours
img_contours=np.copy(img)
# 3rd parm: To draw all the contours in an image (-1) or To draw an individual contour, say 3th contour (2)
# 4th & 5th parm: color and thickness prespectively :)
cv2.drawContours(img_contours, contours[0], -1, (255, 0, 0), 5)
# show_images([img_contours],['Contours'])



19


array([[[196, 184, 178],
        [193, 181, 175],
        [194, 182, 176],
        ...,
        [159, 178, 183],
        [171, 191, 196],
        [181, 203, 208]],

       [[203, 191, 185],
        [200, 188, 182],
        [200, 188, 182],
        ...,
        [151, 170, 175],
        [162, 182, 187],
        [171, 193, 198]],

       [[203, 191, 185],
        [201, 189, 183],
        [202, 190, 184],
        ...,
        [113, 130, 133],
        [135, 154, 157],
        [152, 173, 175]],

       ...,

       [[ 37,  40,  45],
        [ 37,  40,  45],
        [ 29,  32,  37],
        ...,
        [148, 162, 191],
        [156, 170, 199],
        [163, 177, 206]],

       [[ 27,  30,  35],
        [ 32,  35,  40],
        [ 28,  31,  36],
        ...,
        [149, 163, 192],
        [154, 168, 197],
        [159, 173, 202]],

       [[ 21,  24,  29],
        [ 20,  23,  28],
        [ 18,  21,  26],
        ...,
        [156, 170, 199],
        [147, 161, 190],
        [146, 160, 189]]

In [6]:
import cv2
import numpy as np
 
image_original = cv2.imread('car/test.png')
# cv2.imshow("Original", image_original)
 
result = image_original.copy()
 
image = cv2.cvtColor(image_original, cv2.COLOR_BGR2HSV)
 
# lower boundary RED color range values; Hue (0 - 10)
lower1 = np.array([0, 100, 20])
upper1 = np.array([10, 255, 255])

# upper boundary RED color range values; Hue (160 - 180)
lower2 = np.array([160,100,20])
upper2 = np.array([179,255,255])
 
lower_mask = cv2.inRange(image, lower1, upper1)
upper_mask = cv2.inRange(image, lower2, upper2)
 
full_mask = lower_mask + upper_mask;
 
result = cv2.bitwise_and(result, result, mask=full_mask)
 
# cv2.imshow('mask', full_mask)
# cv2.imshow('result', result)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#Getting Contours in image
# 1st parm: source image
# 2nd parm: contour retrieval mode
# 3rd parm: contour approximation method cv2.CHAIN_APPROX_SIMPLE[Memory saved not all points are stored]
#o/p: the contours and hierarchy.
contours, hierarchy = cv2.findContours(full_mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#Sort Contours Descending
contours = sorted(contours, key=cv2.contourArea, reverse=True)
print(len(contours))
# print((contours))


#Draw Contours
img_contours=np.copy(result)
# 3rd parm: To draw all the contours in an image (-1) or To draw an individual contour, say 3th contour (2)
# 4th & 5th parm: color and thickness prespectively :)
# countors_image=np.copy(image_original)
# cv2.drawContours(countors_image, contours[0], -1, (255, 0, 0), 5)
# show_images([countors_image],['Contours'])
# print(np.shape(countors_image))


# print(contours[0])

# Draming Rectangle :D
rectangle_image=np.copy(image_original)
rect = cv2.minAreaRect(contours[0])
box = cv2.boxPoints(rect)
box = np.int0(box)
cv2.drawContours(rectangle_image,[box],0,(0,255,0),10)



#Getting Center and angle of rotation of Rectangle
((x, y), (width, height), angle_of_rotation) = cv2.minAreaRect(box)
hCar= int(max(width, height))
wCar= int(min(width, height))
xCar=int(x)
yCar=int(y)
print("x:",xCar,"y:",yCar,"width:",wCar,"height:",hCar)
print(angle_of_rotation)

# show_images([rectangle_image],['Car Rectangle'],BGR=True)

print(box)
print(rect)

# print(box.angle)

147
x: 655 y: 248 width: 57 height: 77
51.80131912231445
[[607 250]
 [668 202]
 [703 247]
 [642 295]]
((655.4510498046875, 249.0741729736328), (57.5135612487793, 77.67701721191406), 51.842769622802734)


In [8]:
p=3

img=cv2.imread('car/test.png')
bina=toBianry(img)
bina[(bina==255)]=1
cv2.imshow('image',img)
cv2.imshow('binary',bina*255)
# show_images(binary_image)
prvx=xCar
prvy=yCar
sizey=bina.shape[0]
sizex=bina.shape[1]
threshx=int(sizex/40)
threshy=int(sizey/40)
# print(threshx,threshy)
find=0
while (prvx<sizex and prvy < sizey and find<p*hCar):
    curx=int(prvx)
    cury=int(prvy)
    if(int(angle_of_rotation)==90):
        cury-=1
    elif(int(angle_of_rotation)==270):
        cury+=1
    elif(angle_of_rotation>=0.0 and angle_of_rotation <=45.0):
        #increase x and decrease y because we go up and right
        curx+=1
        cury-=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) > angle_of_rotation):
            cury+=1
    elif (angle_of_rotation>45.0 and angle_of_rotation <90.0):
        cury-=1
        curx+=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) < angle_of_rotation):
            curx-=1
    
    elif (angle_of_rotation>90.0 and angle_of_rotation <=135.0):
        temp_angle=180-angle_of_rotation
        cury-=1
        curx-=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) < temp_angle):
            curx+=1
    elif (angle_of_rotation>135.0 and angle_of_rotation <=180.0):
        temp_angle=180-angle_of_rotation
        curx-=1
        cury-=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) > temp_angle):
            cury+=1
    elif (angle_of_rotation>180.0 and angle_of_rotation <=225.0):
        temp_angle=angle_of_rotation-180
        curx-=1
        cury+=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) > temp_angle):
            cury-=1
    elif (angle_of_rotation>225.0 and angle_of_rotation <270):
        temp_angle=angle_of_rotation-180
        cury+=1
        curx-=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) < temp_angle):
            curx+=1
            
    elif (angle_of_rotation>270.0 and angle_of_rotation <=315.0):
        temp_angle=360-angle_of_rotation
        cury+=1
        curx+=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) < temp_angle):
            curx-=1
    elif (angle_of_rotation>315.0 and angle_of_rotation <360.0):
        temp_angle=360-angle_of_rotation
        cury+=1
        curx+=1
        slop=abs(float((yCar-cury))/(xCar-curx))
        if(math.degrees(math.atan(slop)) > temp_angle):
            cury-=1
    
        
#     print(curx,cury)
#     print(bina[cury-5:cury+5,curx-5:curx+5])
    there=False
    for i in range (0,threshx):
        for j in range (0,threshy):
            there |=  bina[cury-i,curx-j]
    for i in range (0,threshx):
        for j in range (0,threshy):
            there |=  bina[cury+i,curx+j]
    if(curx<sizex and cury < sizey and there):
        prvx=curx
        prvy=cury
        find+=1
    else :
        print(curx,cury,there)
        print(bina[cury-threshx:cury+threshx,curx-threshy:curx+threshy])
        cv2.imshow('error',bina[cury-threshx:cury+threshx,curx-threshy:curx+threshy])
        break
print(find)
print(hCar)
print(find==p*hCar)
if(find<p*hCar):
    print('there is no way in front of the car')
else :
    print('there is a way in front of the car')
# print(prvx)
# print(prvy)

795 70 0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
177
77
False
there is no way in front of the car


# 